id: P001804
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16595
  title: ཆུང་བཅོས་བདུད་རྩི་བུམ་པ།
  author: ''
  volumes:
    ec6baedfacf7486ab15a1245a74e42c7:
      image_group_id: I2PD18308
      title: ''
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
